/**
 * Centralised label-builder so /new and /[id] product pages don't duplicate
 * the long t() ↔ key mapping.
 */
type T = (key: string) => string;

export function buildProductFormLabels(t: T) {
  return {
    field_part_code: t("field_part_code"),
    field_manufacturer: t("field_manufacturer"),
    field_manufacturer_none: t("field_manufacturer_none"),
    field_manufacturer_add: t("field_manufacturer_add"),
    field_manufacturer_placeholder: t("field_manufacturer_placeholder"),
    field_slug: t("field_slug"),
    field_slug_hint: t("field_slug_hint"),
    field_condition: t("field_condition"),
    field_condition_new: t("field_condition_new"),
    field_condition_refurbished: t("field_condition_refurbished"),
    field_condition_used: t("field_condition_used"),
    field_price: t("field_price"),
    field_cost_price: t("field_cost_price"),
    field_stock: t("field_stock"),
    field_storage_location: t("field_storage_location"),
    field_category: t("field_category"),
    field_subcategory: t("field_subcategory"),
    field_category_none: t("field_category_none"),
    field_subcategory_none: t("field_subcategory_none"),
    field_category_add: t("field_category_add"),
    field_subcategory_add: t("field_subcategory_add"),
    field_category_placeholder: t("field_category_placeholder"),
    field_subcategory_placeholder: t("field_subcategory_placeholder"),
    field_subcategory_disabled_hint: t("field_subcategory_disabled_hint"),
    field_active: t("field_active"),
    field_featured: t("field_featured"),
    field_warranty: t("field_warranty"),
    field_has_warranty: t("field_has_warranty"),
    field_weight: t("field_weight"),
    field_width: t("field_width"),
    field_height: t("field_height"),
    field_length: t("field_length"),
    field_rib_count: t("field_rib_count"),
    section_custom_specs: t("section_custom_specs"),
    section_custom_specs_hint: t("section_custom_specs_hint"),
    field_custom_spec_label: t("field_custom_spec_label"),
    field_custom_spec_value: t("field_custom_spec_value"),
    field_custom_spec_add: t("field_custom_spec_add"),
    field_image_url: t("field_image_url"),
    field_name_ro: t("field_name_ro"),
    field_name_en: t("field_name_en"),
    field_name_ru: t("field_name_ru"),
    field_description_ro: t("field_description_ro"),
    field_description_en: t("field_description_en"),
    field_description_ru: t("field_description_ru"),
    section_codes: t("section_codes"),
    section_codes_hint: t("section_codes_hint"),
    field_oem_codes: t("field_oem_codes"),
    field_oem_placeholder: t("field_oem_placeholder"),
    field_cross_refs: t("field_cross_refs"),
    field_cross_refs_brand: t("field_cross_refs_brand"),
    field_cross_refs_code: t("field_cross_refs_code"),
    field_cross_refs_add: t("field_cross_refs_add"),
    section_bus: t("section_bus"),
    field_bus_makes: t("field_bus_makes"),
    field_bus_makes_add: t("field_bus_makes_add"),
    field_bus_makes_placeholder: t("field_bus_makes_placeholder"),
    field_bus_makes_empty: t("field_bus_makes_empty"),
    section_basic: t("section_basic"),
    section_pricing: t("section_pricing"),
    section_category: t("section_category"),
    section_specs: t("section_specs"),
    section_names: t("section_names"),
    section_descriptions: t("section_descriptions"),
    section_promo: t("section_promo"),
    field_is_promo: t("field_is_promo"),
    field_promo_price: t("field_promo_price"),
    field_promo_starts: t("field_promo_starts"),
    field_promo_ends: t("field_promo_ends"),
    promo_hint: t("promo_hint"),
    save: t("common_save"),
    saving: t("common_saving"),
    create: t("common_create"),
    creating: t("common_creating"),
    delete: t("common_delete"),
    confirm_delete: t("confirm_delete"),
    cancel: t("common_cancel"),
    required: t("common_required"),
    error_generic: t("common_error"),
  };
}
